### ISSUE TITLE
failed to visit the 'kinect300' website you given

### ISSUE THREAD

**Issue by liuqiskan** [Rowl1ng/MyWiki#1]
https://github.com/Rowl1ng/MyWiki/blob/068e1cba99f60ead176ba0967dbdbcbaf2f95018/computer-graphics/3d-model.html#L2088
The link you offered here seems no longer available, could you please update it or  share a cached version on network drive?

**Comment by Rowl1ng** [comment]
Sorry. I can’t provide the dataset recently. Because the dataset is on my desktop back in university. But due to the Covid-19 I work remotely now and unluckily I can’t access my desktop these days.

Once I get access to my desktop I can share you the file.
在 2020年6月30日 +0800 01:49，liuqiskan <notifications@github.com>，写道：

**Comment by liuqiskan** [comment]
thank you! Waiting for your update

**Comment by Rowl1ng** [comment]
Hi,

I finally recovered the Kinect300 dataset. Sorry for the long long delay.

Best,
Ling
在 2020年7月2日 +0100 12:47，liuqiskan ***@***.***>，写道：
